# Generated by Django 2.0.3 on 2018-03-19 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hh_vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_from', models.CharField(max_length=20)),
                ('salary_to', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=20)),
                ('gross', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('area_name', models.CharField(max_length=20)),
                ('responsibility', models.TextField()),
                ('requirement', models.TextField()),
                ('vacancy_id', models.IntegerField()),
                ('employer_name', models.CharField(max_length=20)),
                ('employer_id', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_from', models.CharField(max_length=20)),
                ('salary_to', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('responsibility', models.TextField()),
                ('requirement', models.TextField()),
                ('experience', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Сompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
