# Generated by Django 2.0.3 on 2018-03-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_vacancy',
            name='currency',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hh_vacancy',
            name='gross',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hh_vacancy',
            name='salary_from',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hh_vacancy',
            name='salary_to',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_from',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_to',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
