# Generated by Django 2.0.3 on 2018-03-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180324_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_vacancy',
            name='employer_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
