# Generated by Django 2.0.3 on 2018-03-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180324_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_vacancy',
            name='area_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hh_vacancy',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hh_vacancy',
            name='requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hh_vacancy',
            name='vacancy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
