# Generated by Django 2.0.3 on 2018-03-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180325_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_vacancy',
            name='employer_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
