# Generated by Django 2.0.3 on 2018-03-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180325_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
