# Generated by Django 2.0.3 on 2018-04-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180331_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibility',
            name='associated',
            field=models.TextField(blank=True, null=True),
        ),
    ]
