# Generated by Django 2.0.3 on 2018-04-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180403_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_vacancy',
            name='employer_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vendors_technologies',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendors_technologies',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
