# Generated by Django 2.0.3 on 2018-04-03 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_auto_20180403_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors_technologies_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name_vendor_tehn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Vendors_technologies')),
            ],
        ),
    ]
