# Generated by Django 2.0.3 on 2018-04-03 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_vendors_technologies_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors_technologies_link',
            name='name_vendor_tehn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='blog.Vendors_technologies'),
        ),
    ]
